### ISSUE TITLE
Handle multiple files with same name in a project

### ISSUE THREAD

**Issue by sachintyagi22** [mast-group/tassal#1]
Currently during the topic training, the tokenized files for a project are stored in a single directory. So a file with a same name (in different directory of the project) will overwrite the earlier tokenized file with that name. This breaks the folding for the first (or all n-1) file.

**Comment by jfowkes** [comment]
Yes this is indeed an issue with the current implementation, many thanks for reporting and submitting a fix.

**Comment by jfowkes** [comment]
Fixed by #2.
